name: Installation tests

on:
  push:
    # Run post-submit tests when pushing to master.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
        pip3 install setuptools
        pip3 install pytest
        pip3 install -r ./requirements.txt
    - name: Install qsim from test PyPI
      # Dependencies can't be installed in this call since we're pulling
      # from the test server.
      run: pip3 install --no-deps -i https://test.pypi.org/simple/ qsimcirq
    - name: Run Python tests
      # Tests cannot be run in the qsim directory, as Python will attempt
      # to import from the local `qsimcirq` instead of the installed module.
      run: |
        mkdir test-dir
        cp -r qsimcirq_tests/ test-dir/
        cd test-dir
        python3 -m pytest ./
