name: Installation tests

on:
  push:
    # Run post-submit tests when pushing to master.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
        pip3 install cmake pytest setuptools
        pip3 install -r ./requirements.txt
    - name: Install qsim from test PyPI
      run: pip3 install -i https://test.pypi.org/simple/ qsimcirq
    - name: Run Python tests
      run: python3 -m pytest interfaces/tests/
